# Generated by Django 5.2.7 on 2025-10-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_alter_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
